apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: efs-teamcity-pvc
  namespace: {{ .Values.namespace }}
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: efs-sc
  resources:
    requests:
      storage: 1Gi
